from pathlib import Path

KERNEL = Path(__file__).resolve().parents[1] / "FluidX3D-master" / "src" / "kernel.cpp"

# Replace the native graphics_streamline body with a two-pass filter.  A line
# is rejected before any draw_line() call unless its traced path enters the
# vehicle-contact radius.  This is intentionally done in the OpenCL kernel,
# rather than in the Python visualizer, because the native FluidX3D graphics
# path is what actually draws the lines.
OLD = '''\t//draw_circle(p, 0.5f*def_streamline_sparse, 0xFFFFFF, camera_cache, bitmap, zbuffer);\n\tfor(float dt=-1.0f; dt<=1.0f; dt+=2.0f) { // integrate forward and backward in time\n\t\tfloat3 p0, p1=p;\n\t\tfor(uint l=0u; l<def_streamline_length/2u; l++) {\n\t\t\tconst uint x = (uint)(p1.x+1.5f*(float)def_Nx)%def_Nx;\n\t\t\tconst uint y = (uint)(p1.y+1.5f*(float)def_Ny)%def_Ny;\n\t\t\tconst uint z = (uint)(p1.z+1.5f*(float)def_Nz)%def_Nz;\n\t\t\tconst uxx n = (uxx)x+(uxx)(y+z*def_Ny)*(uxx)def_Nx;\n\t\t\tif(flags[n]&(TYPE_S|TYPE_E|TYPE_I|TYPE_G)) return;\n\t\t\tconst float3 un = load3(n, u); // interpolate_u(p1, u)\n\t\t\tconst float ul = length(un);\n\t\t\tp0 = p1;\n\t\t\tp1 += (dt/ul)*un; // integrate forward in time\n\t\t\tif(def_scale_u*ul<0.1f||p1.x<-hLx||p1.x>hLx||p1.y<-hLy||p1.y>hLy||p1.z<-hLz||p1.z>hLz) break;\n\t\t\tint c = 0; // coloring\n\t\t\tswitch(field_mode) {\n\t\t\t\tcase 0: c = colorscale_rainbow(def_scale_u*ul); break; // coloring by velocity\n\t\t\t\tcase 1: c = colorscale_twocolor(0.5f+def_scale_rho*(rho[n]-1.0f)); break; // coloring by density\n)+"#ifdef TEMPERATURE"+R(\n\t\t\t\tcase 2: c = colorscale_iron(0.5f+def_scale_T*(T[n]-def_T_avg)); break; // coloring by temperature\n)+"#endif"+R( // TEMPERATURE\n\t\t\t}\n\t\t\tdraw_line(p0, p1, c, camera_cache, bitmap, zbuffer);\n\t\t}\n\t}\n'''

NEW = '''\t// First pass: reject the seed unless its streamline is actually affected by\n\t// the vehicle.  A path counts as affected when it enters this radius around\n\t// a TYPE_S vehicle surface voxel.  No pixels are drawn during this pass.\n\tbool affected = false;\n\tconst int contact_radius = 4;\n\tconst int contact_radius2 = contact_radius*contact_radius;\n\tfor(float dt=-1.0f; dt<=1.0f && !affected; dt+=2.0f) {\n\t\tfloat3 p1=p;\n\t\tfor(uint l=0u; l<def_streamline_length/2u; l++) {\n\t\t\tconst int x=(int)(p1.x+1.5f*(float)def_Nx)%(int)def_Nx;\n\t\t\tconst int y=(int)(p1.y+1.5f*(float)def_Ny)%(int)def_Ny;\n\t\t\tconst int z=(int)(p1.z+1.5f*(float)def_Nz)%(int)def_Nz;\n\t\t\tconst uxx n=(uxx)x+(uxx)(y+z*(int)def_Ny)*(uxx)def_Nx;\n\n\t\t\tfor(int dz=-contact_radius; dz<=contact_radius && !affected; dz++) {\n\t\t\t\tfor(int dy=-contact_radius; dy<=contact_radius && !affected; dy++) {\n\t\t\t\t\tfor(int dx=-contact_radius; dx<=contact_radius; dx++) {\n\t\t\t\t\t\tif(dx*dx+dy*dy+dz*dz>contact_radius2) continue;\n\t\t\t\t\t\tconst int xx=x+dx, yy=y+dy, zz=z+dz;\n\t\t\t\t\t\tif(xx<0 || xx>=(int)def_Nx || yy<0 || yy>=(int)def_Ny || zz<0 || zz>=(int)def_Nz) continue;\n\t\t\t\t\t\tconst uxx nn=(uxx)xx+(uxx)(yy+zz*(int)def_Ny)*(uxx)def_Nx;\n\t\t\t\t\t\tif(flags[nn]&TYPE_S) { affected=true; break; }\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t\tif(affected || (flags[n]&(TYPE_E|TYPE_I|TYPE_G))) break;\n\t\t\tconst float3 un=load3(n,u);\n\t\t\tconst float ul=length(un);\n\t\t\tif(ul<=0.0f) break;\n\t\t\tp1+=(dt/ul)*un;\n\t\t\tif(def_scale_u*ul<0.1f || p1.x<-hLx || p1.x>hLx || p1.y<-hLy || p1.y>hLy || p1.z<-hLz || p1.z>hLz) break;\n\t\t}\n\t}\n\tif(!affected) return;\n\n\t// Second pass: only now draw the complete affected streamline.\n\tfor(float dt=-1.0f; dt<=1.0f; dt+=2.0f) {\n\t\tfloat3 p0, p1=p;\n\t\tfor(uint l=0u; l<def_streamline_length/2u; l++) {\n\t\t\tconst uint x=(uint)(p1.x+1.5f*(float)def_Nx)%def_Nx;\n\t\t\tconst uint y=(uint)(p1.y+1.5f*(float)def_Ny)%def_Ny;\n\t\t\tconst uint z=(uint)(p1.z+1.5f*(float)def_Nz)%def_Nz;\n\t\t\tconst uxx n=(uxx)x+(uxx)(y+z*def_Ny)*(uxx)def_Nx;\n\t\t\tif(flags[n]&(TYPE_S|TYPE_E|TYPE_I|TYPE_G)) break;\n\t\t\tconst float3 un=load3(n,u);\n\t\t\tconst float ul=length(un);\n\t\t\tif(ul<=0.0f) break;\n\t\t\tp0=p1;\n\t\t\tp1+=(dt/ul)*un;\n\t\t\tif(def_scale_u*ul<0.1f || p1.x<-hLx || p1.x>hLx || p1.y<-hLy || p1.y>hLy || p1.z<-hLz || p1.z>hLz) break;\n\t\t\tint c=0;\n\t\t\tswitch(field_mode) {\n\t\t\t\tcase 0: c=colorscale_rainbow(def_scale_u*ul); break;\n\t\t\t\tcase 1: c=colorscale_twocolor(0.5f+def_scale_rho*(rho[n]-1.0f)); break;\n)+"#ifdef TEMPERATURE"+R(\n\t\t\t\tcase 2: c=colorscale_iron(0.5f+def_scale_T*(T[n]-def_T_avg)); break;\n)+"#endif"+R(\n\t\t\t}\n\t\t\tdraw_line(p0,p1,c,camera_cache,bitmap,zbuffer);\n\t\t}\n\t}\n'''

s=KERNEL.read_text(encoding="utf-8")
if OLD in s:
    s=s.replace(OLD,NEW,1)
    KERNEL.write_text(s,encoding="utf-8")
else:
    # Refuse to silently weaken a different kernel.  The build should fail
    # rather than accidentally leaving the old all-streamlines behavior.
    raise RuntimeError("Native graphics_streamline block not found; no kernel change was made.")
